blog/urls.py
from django.urls import path
from .views import HomeView, PostDetailView, AddPostView, AddCommentView,AddReplyView,UpdatePostView,LikeView,DeletePostView, AddCategoryView,CategoryPost, CategoryList


app_name = 'blog'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('article/<int:pk>/', PostDetailView.as_view(), name='article-detail'),
    path('add_post/', AddPostView.as_view(), name='add-post'),
    path('add_category/', AddCategoryView.as_view(), name='add-category'),
    path('article/edit/<int:pk>/', UpdatePostView.as_view(), name='update_post'),
    path('article/<int:pk>/delete/', DeletePostView.as_view(), name="delete-post"),
    path('category/<str:cats>/', CategoryPost, name='category'),
    path('categort_menu',CategoryList, name='category-menu' ),
    path('like/<int:pk>/', LikeView, name='like_post'),
    path('article/<int:pk>/comment', AddCommentView.as_view(), name='add_comment'),
    path('article/comment/<int:pk>/reply/', AddReplyView.as_view(), name='add_reply'),
    
   
]

blogp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('member/', include('django.contrib.auth.urls')),
    path('member/', include('member.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from .views import RegisterUserView, DetailedUserProfileView,UpdateUserProfileView,UserEditView, PassWordChangingView,CreateUserProfileView
from django.contrib.auth import views as auth_views


app_name = 'member'
urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('edit_profile/', UserEditView.as_view(), name='edit-profile'),
    path('create_new_profile/', CreateUserProfileView.as_view(), name='create_profile'),
    path('password/', PassWordChangingView.as_view(), ),
    path('profile/<int:pk>/', DetailedUserProfileView.as_view(), name='profile_detail'),
    path('profile/<int:pk>/update/', UpdateUserProfileView.as_view(), name='profile_detail_update'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.models import User
import datetime
from django.utils import timezone
from ckeditor.fields import RichTextField

class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('blog:home')
    
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_picture =  models.ImageField(null=True, blank=True, upload_to='profile_pictures/')
    facebook_url =  models.CharField(max_length=250)
    twitter_url = models.CharField(max_length=250)
    instagram_url = models.CharField(max_length=250)

    def get_absolute_url(self):
        return reverse('blog:home')
    
    def __str__(self):
        return self.user.username

    
class Post(models.Model):
    title = models.CharField(max_length=150)
    header_image = models.ImageField(null=True, blank=True, upload_to='images/')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null=True)
    published = models.DateTimeField(auto_now=True)
    category = models.CharField(max_length=150, default='Coding')
    likes = models.ManyToManyField(User, related_name='blog_post')
    snippet = models.CharField(max_length=250, default='Click link')

    def get_total_like(self):
        return self.likes.count()




    def __str__(self):
        return  self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse('blog:home')
    

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class meta:
        ordering = ['-date_added ']

    
    def __str__(self):
        return '%s - %s' %(self.post.title , self.name)

class Reply(models.Model):
    comment = models.ForeignKey(Comment, related_name='replies', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body =body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class meta:
        ordering = ['-date_added ']

    def __str__(self):
        return '%s - %s' %(self.comment.post.title , self.body)

blog/forms.py
from django import forms
from . models import Post, Category, Comment, Reply

choice = Category.objects.all().values_list('name', 'name')

choice_list = []
for item in choice:
    choice_list.append(item)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields =('title','author','header_image', 'category', 'body', 'snippet')

        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
           #'author' : forms.Select(attrs={'class':'form-control','value':'', 'id':'user'}),
            'author' : forms.TextInput(attrs={'class':'form-control', 'value':'', 'id':'elder', 'type':'hidden'}),
            'category': forms.Select(choices=choice_list ,attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'snippet':forms.Textarea(attrs={'class': 'form-control'}),


        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields =('name', 'body')

        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control'}),

            'body': forms.Textarea(attrs={'class': 'form-control'}),
            


        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields =('name', 'body')

        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control'}),

            'body': forms.Textarea(attrs={'class': 'form-control'}),
            


        }
    


class EditpostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields =('title', 'body')

        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),

        }
            

        

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Comment, Reply, Profile
from django.views.generic import ListView, DetailView,CreateView,UpdateView, DeleteView
from.forms import EditpostForm, PostForm, CommentForm, ReplyForm
from django.urls import reverse_lazy,reverse
from django.http import HttpResponseRedirect

def LikeView(request, pk):
    post = get_object_or_404(Post, id = request.POST.get('post_id'))
    Liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        Liked = False
    else:
        post.likes.add(request.user)
        Liked = True
    return HttpResponseRedirect(reverse('blog:article-detail', args = [str(pk)]))
    
class HomeView(ListView):
    models = Post
    template_name = 'home.html'

    def get_queryset(self):
        return Post.objects.order_by('-published')


    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context 

    
        
def CategoryList(request):
    categorylist = Category.objects.all()
    return render(request, 'cate_list.html', {'categorylist': categorylist})
        
class PostDetailView(DetailView):
    model = Post
    template_name = 'detail.html'

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(PostDetailView, self).get_context_data(*args, **kwargs)
        stuff = get_object_or_404(Post, id = self.kwargs['pk'])
        total_likes = stuff.get_total_like()
        Liked = False
        if stuff.likes.filter(id = self.request.user.id).exists():
            Liked = True
        context["cat_menu"] = cat_menu
        context["total_likes"] = total_likes
        context["Liked"] = Liked
        return context 


class AddPostView(CreateView):
    model = Post
    template_name = 'the_post.html'
    #fields = ['title', 'body']
    form_class = PostForm

class AddCommentView(CreateView):
    model = Comment
    template_name = 'add_comment.html'
    #fields = '__all__'
    form_class = CommentForm
    success_url = reverse_lazy('blog:home')
    
    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

class AddReplyView(CreateView):
    model = Reply
    template_name = 'add_reply.html'
    #fields = '__all__'
    form_class = ReplyForm
    success_url = reverse_lazy('blog:home')

    
    def form_valid(self, form):
        form.instance.comment_id = self.kwargs['pk']
        return super().form_valid(form)


def CategoryPost(request, cats):
    
    category_post = Post.objects.filter(category=cats.replace('-', ' '))
    return render(request, 'category.html', {
        'cats':cats.title().replace('-', ' '), 'category_post':category_post})


class AddCategoryView(CreateView):
    model = Category
    template_name = 'cate.html'
    fields = '__all__'
    #form_class = PostForm


class UpdatePostView(UpdateView):
    model = Post 
    template_name = 'update_post.html'
    #fields = ['title', 'body']
    form_class = EditpostForm


class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('blog:home')

blog/templates/add_comment.html
{% extends 'base.html'%}
{% block title%}Create A Comment {% endblock %}
{% block content %}
<div class="container align-items-center justify-content-start">

    <h1> Add Comment </h1>
    <div class="form-group">
    <form method="POST" >
        {% csrf_token %}


        {{ form.as_p}}
        
        <button class="btn btn-secondary">Add Comment<button>

    </div>


    
{% endblock %}

blog/templates/add_reply.html
{% extends 'base.html'%}
{% block title%}Create A Comment {% endblock %}
{% block content %}
<div class="container align-items-center justify-content-start">

    <h1> Reply </h1>
    <div class="form-group">
    <form method="POST" >
        {% csrf_token %}


        {{ form.as_p}}
        
        <button class="btn btn-secondary">Reply<button>

    </div>


    
{% endblock %}

blog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/element.css' %}">
    </head>
  
    <title>{% block title %} my awesome blog {% endblock %}</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{% url 'blog:home' %}">Sixtus blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          {% if cat_menu %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% for item in cat_menu %}
                    <a class="dropdown-item" href="{% url 'blog:category' item|slugify %}"> {{ item }}</a>
                  {% endfor %}
                  
                  </div>
              </li>
              {%else%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:category-menu'%}">Categories </a>
              </li>
              {%endif%}

              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog:add-post'%}">Add post </a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog:add-category'%}">Add Category </a>
                </li>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Profile
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.profile.id %}
                            <a class="dropdown-item" href="{% url 'member:profile_detail' user.profile.id %}"> Show profile </a>
                            <a class="dropdown-item" href="{% url 'member:profile_detail_update' user.profile.id %}"> Edit profile </a>
                            <a class="dropdown-item" href="{% url 'member:edit-profile'  %}"> Edit settings </a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'member:create_profile'  %}"> Create profile </a>
                            
                        {% endif %}
                        
                        
                    
                      </div>
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
              
              {%else%}
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'member:register'%}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
              {%endif%}
            </ul>
          </div>
        </nav>
    
                    
      {% block content %}

      {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  
    <script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
    <script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
    <script src="{% static 'plugins/Isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'plugins/scrollTo/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'plugins/easing/easing.js' %}"></script>
    <script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/cate.html
{% extends 'base.html'%}
{% block title%}Create Category{% endblock %}
{% block content %}
<div class="container align-items-center justify-content-start">
{% if user.is_authenticated %}
    <h1> Add Category </h1>
    <div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <button class="btn btn-secondary">Add<button>

    </div>
    {% else %}
        <h1> You're not logged in!! </h1>
    {% endif %}
</div>
{% endblock %}

blog/templates/cate_list.html
{% extends 'base.html' %}

{% block title%} Blog Category {%endblock %}
{% block content %}
<div class="container align-items-center justify-content-start">
<h1 style="font-family: Arial, Helvetica, sans-serif;"> Blog Categories</h1>
<ul>
{% for category in categorylist %}
<li style="list-style-type: square;"><a href="{% url 'blog:category' category|slugify %}">
     {{ category}}</a></li>
{% endfor %}
</ul>
</div>
{% endblock %}

blog/templates/category.html
{% extends 'base.html'%}
{% block title%} {{cats}} category {% endblock %}

{% block content %}
<div class="container align-items-center justify-content-start">
<h1>{{ cats }}</h1>
{% if category_post %}
<ul>
    {% for post in category_post  %}
    <li><a href="{% url 'blog:article-detail' post.pk %}">{{post.title}} </a> 
    {{post.author.first_name}} {{ post.author.last_name }}  

    {% if user.is_authenticated %}
    <small>
        - <a href="{% url 'blog:update_post' post.pk %}">[Edit]</a> 
            <a href="{% url 'blog:delete-post' post.pk %}">[Delete]</a>
        </small>

    {% endif %}
    <p class="date">Published : {{post.published}}</p><br>
    {{post.body|slice:":200"|safe}}</li>
    {% endfor %}
</ul>
{% else %}
<p> sorry this page doesn't exist </p>
{% endif %}
</div>
{% endblock %}

blog/templates/delete_post.html
{% extends 'base.html' %}


{% block title %} Delete post {% endblock %}
{% block content %}
<div class="container align-items-center justify-content-start">
{% if user.is_authenticated %}
    {% if user.id == post.author.id %}
    <h1> Delete post {{post.title}} </h1><br/>
    <div>
    <form method="POST">
        {%csrf_token%}
        <h3> Are you sure you?</h3> <br>
        <button class="btn btn-secondary"> Delete Post</button>

    </div>
    {% else %}
    <p> Oops!!! you cannot delete this post..</p>
    {% endif%}
{% else %}
    <h3> You're not login </h3>
{% endif %}
</div>
{% endblock %} 

blog/templates/detail.html
{% extends 'base.html'%}
{% load static %}
{% block title %}{{post.title}}{% endblock %}
{% block content %}

<div class="container align-items-center justify-content-start">
<h1>{{post.title}} {{post.author.id}}</h1>

 By: {{post.author}} 
    {% if user.is_authenticated %}
        {% if user.id == post.author.id %}
        - 
        <small><a href="{% url 'blog:update_post' post.pk %}">Edit</a>
            <a href="{% url 'blog:delete-post' post.pk %}">[Delete]</a><br></small>
        <hr>
        <br/>
        {%endif%}
    {% endif %}
    <p><img src="{{post.header_image.url}}" width="300"></p>
    {{post.body|safe}}
    


<br/><br/>
<hr>
     
    <form action="{% url 'blog:like_post' post.pk %}" method="POST">
        {% csrf_token %}
        {% if user.is_authenticated %}
            {% if Liked %}
                <button type="submit" name="post_id" value
                ="{{post.id}}" class="btn btn-danger  btn-sm"> Unlike</button>

                - {{  total_likes }} likes
            {% else%}
                <button type="submit" name="post_id" value
                ="{{post.id}}" class="btn btn-primary  btn-sm"> Like</button> 
                
                - {{  total_likes }} likes
            {% endif%}
        </form>
        {%else%}
             <a href="{% url 'login' %}">login </a> to like  - {{  total_likes }} likes
        {%endif%}

        
        <br/>
        <br/>
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
              {% if post.author.profile_picture %}
                <div class="col-md-4">
                  <img src="{{post.author.profile_picture.url}}" alt="..."  width="170" height="160" />
                </div>
              {% else %}
                <div class="col-md-4">
                  <img src="{% static 'blog/images/images.png' %}" alt="..." width="150" height="120"/>
                </div>
              {% endif %}
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"><a href="{% url 'member:profile_detail' post.author.profile.id %}">{{post.author.first_name}}  {{post.author.last_name}}</a></h5>
                  <p class="card-text"><small class="text-muted">
                    <a href="{{post.author.profile.twitter_url}}"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                | <a href="{{post.author.profile.facebook_url}}"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            |     <a href="{{post.author.profile.instagram_url }}"><i class="fa fa-instagram" aria-hidden="true"></i></a></small></p>
                  <p class="card-text">{{post.author.profile.bio}}</p>
                 
                </div>
              </div>
            </div>
          </div>
          <br/>
        <br/>
        <hr>
        <h2> Comments..</h2>
        <br/>
       
        {% if not post.comments.all %}
          <p> <a href="{% url 'blog:add_comment' post.pk %}"> Add comments </a></p>
        {%else%}
          <p> <a href="{% url 'blog:add_comment' post.pk %}"> Add comments </a></p>
          {% for comment in post.comments.all %}
            <b style="font-size: 15px;">
                <p>{{comment.name}} - 
                {{comment.date_added}}</p>
              </b>
            <p>{{comment.body}}</p>
              
            {% if comment.replies.all %}
              
              {% for reply in comment.replies.all %}
                <small>
                  <em>
                  <b> 
                    {{reply.name}} - 
                    {{reply.date_added}}
                  </b><br>
                    <p>{{reply.body}}</p>
                  </em>
                </small>
              {% endfor %}
              <p> <a href="{% url 'blog:add_reply' comment.pk  %}"> reply <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
              </svg></a></p>
            {%else%}
                <p> <a href="{% url 'blog:add_reply' comment.pk %}"> reply <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
                </svg></a></p>
              
            {%endif%}
          {% endfor %}
          <br/>
          <p> <a href="{% url 'blog:add_comment' post.pk %}"> Add comments </a></p>
        {%endif%}
        
  </div>
{% endblock %}

blog/templates/home.html
{% extends 'base.html'%}
{% block title %} Posts{% endblock %}
{% block content %}
<div class="container align-items-center justify-content-start">
<h1>Posts</h1>

<ul>
    {% for post in object_list %}
    
    <li style="list-style-type: square;"><a href="{% url 'blog:article-detail' post.pk %}">{{post.title}} </a> 
    {{post.author.first_name}} {{ post.author.last_name }} -<a href="{% url 'blog:category' post.category|slugify %}">{{ post.category }} </a>
    
    
    {% if user.is_authenticated %}
    {% if user.id == post.author.id %}
    <small>
        - <a href="{% url 'blog:update_post' post.pk %}">[Edit]</a> 
        -<a href="{% url 'blog:delete-post' post.pk %}">[Delete]</a>
    
        </small>
        {%endif%}
    {% endif %}
    <p class="date">Published : {{post.published}} <br></p> 
    {{post.snippet}}
    </li>
    {% endfor %}
</ul>
</div>

{% endblock %}

blog/templates/the_post.html
{% extends 'base.html'%}
{% block title%}Create post {% endblock %}
{% block content %}
<div class="container align-items-center justify-content-start">
{% if user.is_authenticated %}
    <h1> Add Post </h1>
    <div class="form-group">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media}}

        {{ form.as_p}}
        
        <button class="btn btn-secondary">Post<button>

    </div>

    <script>
        var name = "{{ user.id }}";
        document.getElementById("elder").value
            = name;
    </script>
    
    
    {% else %}
        <h1> You're not logged in!! </h1>
    {% endif %}
</div>
{% endblock %}

blog/templates/update_post.html
{% extends 'base.html'%}

{% block title%}Edit post {% endblock %}
{% block content %}
<div class="container align-items-center justify-content-start">
{% if user.is_authenticated %}
    {% if user.id == post.author.id %}
    <h1> Update post </h1>
    <div class="form-group">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media}}
        {{ form.as_p }}
        <button class="btn btn-secondary">Update<button>

    </div>
    {% else %}
    <p style="font-size: 20px;"> Oops!!! you cannot edit this post..</p>
    {%endif%}
{% else %}
<h1> You're not logged in </h1>

{%endif%}
</div>
{% endblock %}